const en = {
  eyebrow: 'DAILY ORBIT / REWARDS', title: 'Your daily spin', close: 'Close daily wheel',
  intro: 'One free spin every 24 hours. Every spin wins a prize.',
  exclusive: 'EXCLUSIVE COSMETIC', shipSubtitle: 'Crown of the eclipse',
  chance: 'Next spin: {chance}% chance of the skin. Cosmetic only.',
  collected: 'In your collection. The gold slot now awards 500 NOVA.',
  free: 'Spin for free', video: 'Watch video · extra spin',
  pending: 'Save pending prize', saving: 'Saving your prize…', watching: 'Waiting for the video…',
  spinning: 'Your prize is on its way…', skip: 'Show prize now',
  extraNote: 'One extra spin per daily cycle. The video spin can also unlock the exclusive cosmetic.',
  simulation: 'Local test: the video is simulated, not a real advertisement.',
  odds: 'Prizes and probabilities', oddsNote: 'Sectors show prizes, not their odds. Next spin: each NOVA slot {nova}%; gold slot {chance}%.',
  videoOdds: 'Free and video spins use the same odds. If you own the cosmetic, the gold slot awards 500 NOVA.',
  noPity: 'Starts at 1%. Every completed spin adds 1 percentage point for the next spin, up to 20%. No reset on a new day or win, and no guaranteed unlock.',
  next: 'Next free spin in', used: 'Extra spin used', first: 'Use your free spin first',
  freeMode: 'FREE SPIN', videoMode: 'EXTRA VIDEO SPIN', equip: 'Equip cosmetic', equipped: 'Cosmetic equipped',
  saved: 'PRIZE SAVED', unlocked: '{name} unlocked', awarded: 'NOVA added to your wallet',
  full: 'Your NOVA wallet is full', previous: 'LAST SAVED PRIZE',
  busy: 'A spin is already in progress. Wait a moment.', cooldown: 'This spin has already been used. Your progress is up to date.',
  'free-first': 'Use the new free spin before your extra video spin.',
  'storage-error': 'Your prize could not be saved. Free up browser storage and retry; a pending prize does not require another video.',
  recoverClock: 'Restore daily schedule',
  'clock-error': 'Your device clock changed. Restore the schedule: your prizes remain saved and the next free spin unlocks in 24 hours.',
  dismissed: 'Video not completed. Your extra spin is still available.',
  unavailable: 'No video is available right now. Please try again later.',
  unsupported: 'Spins are unavailable in this browser. Open the game over HTTPS or localhost in an updated browser.',
  error: 'The spin could not finish. Your saved prizes are safe; please try again.',
  videoUnavailable: 'Video unavailable', days: 'd', hours: 'h', minutes: 'min', ready: 'FREE SPIN READY'
} as const;
const es: Record<keyof typeof en, string> = {
  eyebrow: 'ÓRBITA DIARIA / PREMIOS', title: 'Tu giro de cada día', close: 'Cerrar ruleta diaria',
  intro: 'Un giro gratis cada 24 horas. Siempre ganas un premio.',
  exclusive: 'SKIN EXCLUSIVA', shipSubtitle: 'Corona del eclipse',
  chance: 'Próximo giro: {chance}% de conseguir la skin. Sólo apariencia, sin ventajas.',
  collected: 'Ya está en tu colección. La ranura dorada ahora entrega 500 NOVA.',
  free: 'Girar gratis', video: 'Ver video · giro extra',
  pending: 'Guardar premio pendiente', saving: 'Guardando tu premio…', watching: 'Esperando el video…',
  spinning: 'Tu premio está en camino…', skip: 'Ver premio ahora',
  extraNote: 'Un extra por ciclo diario. El giro con video también puede desbloquear la skin exclusiva.',
  simulation: 'Prueba local: el video se simula; no es un anuncio real.',
  odds: 'Premios y probabilidades', oddsNote: 'Las ranuras muestran premios, no probabilidades. Próximo giro: cada ranura NOVA {nova}%; dorada {chance}%.',
  videoOdds: 'Gratis y video usan la misma probabilidad. Si ya tienes la skin, la ranura dorada entrega 500 NOVA.',
  noPity: 'Empieza en 1%. Cada giro completado suma un punto porcentual para el siguiente, hasta 20%. No se reinicia al cambiar de día ni al ganar; no garantiza un desbloqueo.',
  next: 'Próximo giro gratis en', used: 'Giro extra utilizado', first: 'Primero usa tu giro gratis',
  freeMode: 'GIRO GRATUITO', videoMode: 'GIRO EXTRA CON VIDEO', equip: 'Equipar skin', equipped: 'Skin equipada',
  saved: 'PREMIO GUARDADO', unlocked: '{name} desbloqueada', awarded: 'NOVA añadida a tu cartera',
  full: 'Tu cartera de NOVA está llena', previous: 'ÚLTIMO PREMIO GUARDADO',
  busy: 'Ya hay un giro en curso. Espera un momento.', cooldown: 'Este giro ya se utilizó. Tu progreso está actualizado.',
  'free-first': 'Usa el nuevo giro gratuito antes del extra con video.',
  'storage-error': 'No se pudo guardar el premio. Libera almacenamiento del navegador y reintenta; un premio pendiente no pide otro video.',
  recoverClock: 'Restablecer horario diario',
  'clock-error': 'Cambió la hora del dispositivo. Restablece el horario: conservas tus premios y el próximo giro gratis se habilita en 24 horas.',
  dismissed: 'El video no se completó. Conservas tu giro extra.',
  unavailable: 'No hay video disponible ahora. Inténtalo más tarde.',
  unsupported: 'Los giros no están disponibles en este navegador. Abre el juego por HTTPS o localhost en un navegador actualizado.',
  error: 'No se pudo terminar el giro. Tus premios guardados están a salvo; vuelve a intentar.',
  videoUnavailable: 'Video no disponible', days: 'd', hours: 'h', minutes: 'min', ready: 'GIRO GRATIS DISPONIBLE'
};
export const dailyWheelCopy = (language: string): Record<keyof typeof en, string> => language.startsWith('es') ? es : en;
